### ISSUE TITLE
raise IndexError("single positional indexer is out-of-bounds") IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by AndrejHatzi** [WiraDKP/RNN_MIDI_Composer#1] opened 2019-02-04 15:24 UTC
Hello, When I use the Folks songs you provided, train.py runs flawlessly, but when I inserted my own .csv models, I got the following error:

Training on CPU

  0%|          | 0/14 [00:00<?, ?it/s]The_Doors_-_Break_on_Through.csv

```
Traceback (most recent call last):
  File "C:\Users\Nietzsche\Desktop\MusicGen\RNN_MIDI_Composer-master\train.py", line 46, in <module>
    main()
  File "C:\Users\Nietzsche\Desktop\MusicGen\RNN_MIDI_Composer-master\train.py", line 31, in main
    note = csv2seq(midi_source_folder, fname, note) # --
  File "C:\Users\Nietzsche\Desktop\MusicGen\RNN_MIDI_Composer-master\utils.py", line 221, in csv2seq
    df_on.durr = [df_off[(df_off.note==note) & (df_off.time > time)].iloc[0, 1] for time, note in zip(df_on.time.values, df_on.note.values)] - df_on.time
  File "C:\Users\Nietzsche\Desktop\MusicGen\RNN_MIDI_Composer-master\utils.py", line 221, in <listcomp>
    df_on.durr = [df_off[(df_off.note==note) & (df_off.time > time)].iloc[0, 1] for time, note in zip(df_on.time.values, df_on.note.values)] - df_on.time
  File "C:\Users\Nietzsche\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 1472, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\Nietzsche\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 2013, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "C:\Users\Nietzsche\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 222, in _has_valid_tuple
    self._validate_key(k, i)
  File "C:\Users\Nietzsche\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 1957, in _validate_key
    self._validate_integer(key, axis)
  File "C:\Users\Nietzsche\AppData\Local\Programs\Python\Python36\lib\site-packages\pandas\core\indexing.py", line 2009, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
I'll provide you with the .csv files I've used!

[dataset.zip](https://github.com/WiraDKP/RNN_MIDI_Composer/files/2828621/dataset.zip)

Thank you,
Andrej Hatzi

**Comment by WiraDKP** [comment] 2019-02-12 10:55
Hi Andrej,
Thank you for opening this issue. 

I have checked your dataset and the problem is that `The_Doors_-_Break_on_Through.csv` is not correctly converted. What I did is simply converting your all of your .csv files back to .mid using midicsv and `Break on through` failed that test.

My recommendation is to try converting the original .mid file again. If the problem persists, it is a bug in midicsv and I think you cannot use that song as train data.

I hope it helps. Can't wait to listen to your generated midi song :)
Thanks

**Comment by AndrejHatzi** [comment] 2019-02-12 11:04
Thank you! I'll try to use another dataset!
I'll keep in touch with you!

**Comment by AndrejHatzi** [comment] 2019-02-12 11:56
I've tried with another dataset, and still the same error occurs!
In your dataset you have [cleaned] what types of changes did you do?
¿And what is n_hidden=64, n_layers=2, bs=128, seq_len=25?, is seq_len the number of files?

Looking forward for your input,
Andrej Hatzi

**Comment by WiraDKP** [comment] 2019-02-14 10:01
Hi @AndrejHatzi,
- Yes, I have tested and indeed there is something wrong. Give me some time and hope that it'll be solved :)
- [cleaned] is just me removing some channels that has uninteresting repetitive sound (i.e. maracas, drums, snare). If we feed too much background music like that, the RNN will learn to produce a repetitive music, which is not interesting.
- For information on the parameters, please check the readme in `Parameters in Training configuration` section.
Thanks

**Comment by WiraDKP** [comment] 2019-02-14 11:08
Hi @AndrejHatzi,
I have found and solved the problem, you should try to pull the repo again.
Turns out that I have missed a special case in midicsv, which is `Note_on_c with 0 velocity mean Note_off_c`.

I have tried to train with your dataset and it works fine now.
Thank you for informing me this issue. You should be able to train your midi composer now.

I'll close this issue. If there are other problem, please don't hesitate to open this issue again.
Thanks

**Closed as completed** 2019-02-14 11:10 UTC
